# encoding: utf-8

# StockDataTemplate.py

# Copyright (c) Ivan Antunović (ivantun05@gmail.com) - All rights reserved.
# Unintended redistribution can be punishable by law.
# By reading this message, you are automatically consenting to it
# and you are accepting that the financial data might be incorrect.
# The financial data generated by this script is for informational purposes only
# and should not be considered as investment advice.
# Use at your own risk.


STOCK_DATA_TEMPLATE = {
    "Company": None,
    "Original Weight": None,
    "P/E (Forward)": None,
    "P/E (Trailing)": None,
    "EBIT/TEV (%)": None,
    "TEV (in Billions)": None,
    "P/B": None,
    "EPS (latest)": None,
    "EVAR - EPS (%)": None,
    "EVAR - Net Income (%)": None,
    "CAGR - EPS (%)": None,
    "CAGR - Net Income (%)": None,
    "Dividend Yield (%)": None,
    "ROE (ttm) - yFinance (%)": None,
    "ROE (ttm) - Calc (%)": None,
    "ROA - yFinance (%)": None,
    "ROA - Calc (%)": None,
    "CFOA (%)": None,
    "GPOA (ttm) (%)": None,
    "GPMAR (ttm) (%)": None,
    "Profit Margin (%)": None,
    "Sector": None,
    "Industry": None,
    "Market Cap (in Billions)": None
}

INVALID_TICKER_TEMPLATE = {
    "Company": None,  # to be set to ticker
    "Original Weight": None,  # to be set to weight
    "P/E (Forward)": "Invalid Ticker!",
    "P/E (Trailing)": "Invalid Ticker!",
    "P/B": "Invalid Ticker!",
    "EBIT/TEV (%)": "Invalid Ticker!",
    "EPS (latest)": "Invalid Ticker!",
    "EVAR - EPS (%)": "Invalid Ticker!",
    "EVAR - Net Income (%)": "Invalid Ticker!",
    "CAGR - EPS (%)": "Invalid Ticker!",
    "CAGR - Net Income (%)": "Invalid Ticker!",
    "Dividend Yield (%)": "Invalid Ticker!",
    "ROE (ttm) - yFinance (%)": "Invalid Ticker!",
    "ROE (ttm) - Calc (%)": "Invalid Ticker!",
    "ROA - yFinance (%)": "Invalid Ticker!",
    "ROA - Calc (%)": "Invalid Ticker!",
    "CFOA (%)": "Invalid Ticker!",
    "GPOA (ttm) (%)": "Invalid Ticker!",
    "GPMAR (ttm) (%)": "Invalid Ticker!",
    "Profit Margin (%)": "Invalid Ticker!",
    "Sector": "Invalid Ticker!",
    "Industry": "Invalid Ticker!",
    "Market Cap (in Billions)": "Invalid Ticker!"
}
