# encoding: utf-8

# StockDataTemplate.py

# Copyright (c) Ivan Antunović (ivantun05@gmail.com) - All rights reserved.
# Unintended redistribution can be punishable by law.
# By reading this message, you are automatically consenting to it
# and you are accepting that the financial data might be incorrect.
# The financial data generated by this script is for informational purposes only
# and should not be considered as investment advice.
# Use at your own risk.


STOCK_DATA_TEMPLATE = {
    "Company": None,
    "Country": None,  # Added country field
    "Original Weight": None,
    "Market Cap (in Billions)": None,
    "P/E (Forward)": None,
    "P/E (Trailing)": None,
    "EBIT/TEV (%)": None,
    "TEV (in Billions)": None,
    "P/B": None,
    "EPS (latest)": None,
    "EVAR - EPS (%)": None,
    "EVAR - Net Income (%)": None,
    "CAGR - EPS (%)": None,
    "CAGR - Net Income (%)": None,
    "Dividend Yield (%)": None,
    "ROE (ttm) - yFinance (%)": None,
    "ROE (ttm) - Calc (%)": None,
    "ROA - yFinance (%)": None,
    "ROA - Calc (%)": None,
    "CFOA (annual) (%)": None,
    "CFOA (ttm) (%)" : None,
    "GPOA (ttm) (%)": None,
    "GPMAR (ttm) (%)": None,
    "Profit Margin (%)": None,
    "Sector": None,
    "Industry": None
}

INVALID_TICKER_TEMPLATE = {
    "Company": None,  # to be set to ticker
    "Country": None,  # to be set to country
    "Original Weight": None,  # to be set to weight
    "Market Cap (in Billions)": "Invalid Ticker!",
    "P/E (Forward)": "N/A",
    "P/E (Trailing)": "N/A",
    "P/B": "N/A",
    "EBIT/TEV (%)": "N/A",
    "TEV (in Billions)": "N/A",
    "EPS (latest)": "N/A",
    "EVAR - EPS (%)": "N/A",
    "EVAR - Net Income (%)": "N/A",
    "CAGR - EPS (%)": "N/A",
    "CAGR - Net Income (%)": "N/A",
    "Dividend Yield (%)": "N/A",
    "ROE (ttm) - yFinance (%)": "N/A",
    "ROE (ttm) - Calc (%)": "N/A",
    "ROA - yFinance (%)": "N/A",
    "ROA - Calc (%)": "N/A",
    "CFOA (annual) (%)": "N/A",
    "CFOA (ttm) (%)" : "N/A",
    "GPOA (ttm) (%)": "N/A",
    "GPMAR (ttm) (%)": "N/A",
    "Profit Margin (%)": "N/A",
    "Sector": "N/A",
    "Industry": "N/A"
}
