# encoding: utf-8

# Copyright (c) Ivan Antunović (ivantun05@gmail.com) - All rights reserved.
# Unintended redistribution can be punishable by law.
# By reading this message, you are automatically consenting to it
# and you are accepting that the financial data might be incorrect.
# The financial data generated by this script is for informational purposes only
# and should not be considered as investment advice.
# Use at your own risk.


class Stock():
    def __init__( self, ticker, sector, value_metrics, profitability_metrics, growth_metrics, safety_metrics ):

        self.ticker = ticker                                # Stock ticker symbol
        self.sector = sector                                # Sector of the stock (e.g., Technology, Healthcare, Financial Services, Industrials, etc.)
        self.value_metrics = value_metrics                  # Value metrics (P/B, P/E, etc.)
        self.profitability_metrics = profitability_metrics  # Profitability metrics
        self.growth_metrics = growth_metrics                # Profitability Growth metrics
        self.safety_metrics = safety_metrics                # Safety metrics